# Tensors , Basic Operations and Activation Functions

## Installing TensorFlow
To install TensorFlow on your local machine you can use pip.
```console
pip install tensorflow
```

## Tensors 
A tensor is a generalization of vectors and matrices to potentially higher dimensions. Internally, TensorFlow represents tensors as n-dimensional arrays of base datatypes.

**Data Types Include**: float32, int32, string and others.

**Shape**: Represents the dimension of data.

Just like vectors and matrices tensors can have operations applied to them like addition, subtraction, dot product, cross product etc.

### Scalar
- A tensor with **zero dimensions**
- Represents a single numerical value

Example:  
x = 5


In [2]:
import torch
scalar = torch.tensor(5)
scalar


tensor(5)

### Vector
- A tensor with **one dimension**
- Represents a list of numbers

Example:  
x = [1, 2, 3]


### Matrix
- A tensor with **two dimensions**
- Represents rows and columns

Example:  
x = [[1, 2],  
     [3, 4]]


In [3]:
matrix = torch.tensor([[1, 2], [3, 4]])
matrix


tensor([[1, 2],
        [3, 4]])

### Higher-Order Tensors
- Tensors with **three or more dimensions**
- Used to represent images, videos, and batches of data

Example:
- 3D tensor → RGB image
- 4D tensor → batch of images


In [4]:
tensor_3d = torch.randn(2, 3, 4)
tensor_3d.shape


torch.Size([2, 3, 4])

### 1. Creating a Tensor from Python Data

Tensors can be created directly from Python lists or nested lists.


In [5]:
import torch

# Scalar
scalar = torch.tensor(10)

# Vector
vector = torch.tensor([1, 2, 3, 4])

# Matrix
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

scalar, vector, matrix


(tensor(10),
 tensor([1, 2, 3, 4]),
 tensor([[1, 2, 3],
         [4, 5, 6]]))

### 2. Creating Tensors with Specific Values

Deep learning frameworks provide functions to create tensors filled with predefined values.


In [7]:
# Tensor filled with zeros
zeros_tensor = torch.zeros(2, 3)

# Tensor filled with ones
ones_tensor = torch.ones(2, 3)

# Identity matrix
identity_tensor = torch.eye(3)

zeros_tensor, ones_tensor, identity_tensor


(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]))

### 3. Creating Random Tensors

Random tensors are widely used to initialize weights in neural networks.


In [9]:
# Random values between 0 and 1
random_uniform = torch.rand(2, 3)

# Random values from normal distribution (mean=0, std=1)
random_normal = torch.randn(2, 3)

random_uniform, random_normal


(tensor([[0.9042, 0.0924, 0.8552],
         [0.7995, 0.1496, 0.0989]]),
 tensor([[-0.6224, -0.5790,  1.2360],
         [ 1.8613,  0.0829, -1.0737]]))

### 4. Creating Tensors with a Specific Data Type

Tensors can be created with specific data types such as integers or floating-point values.


In [10]:
float_tensor = torch.tensor([1, 2, 3], dtype=torch.float32)
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

float_tensor.dtype, int_tensor.dtype


(torch.float32, torch.int32)

### 5. Creating Tensors with a Specific Shape

Sometimes we need tensors of a particular shape for neural network layers.


In [11]:
# Create an empty tensor (values are uninitialized)
empty_tensor = torch.empty(3, 2)

# Create a tensor with the same shape as another tensor
reference = torch.ones(2, 2)
same_shape = torch.zeros_like(reference)

empty_tensor, same_shape


(tensor([[0., 0.],
         [0., 0.],
         [0., 0.]]),
 tensor([[0., 0.],
         [0., 0.]]))

### 6. Creating Tensors Using Ranges

Range-based tensors are useful for indexing and testing.


In [13]:
# Sequence of numbers
range_tensor = torch.arange(0, 10)

# Evenly spaced values
linspace_tensor = torch.linspace(0, 1, steps=5)

range_tensor, linspace_tensor


(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000]))

### 7. Creating Tensors That Track Gradients

For training neural networks, tensors must track gradients.


In [14]:
weights = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
weights


tensor([1., 2., 3.], requires_grad=True)

## Key Points to Remember

- Tensors can be created from lists, predefined values, or random distributions
- Shape, data type, and device are important properties
- Random tensors are commonly used for weight initialization
- Gradient tracking is essential for training neural networks


## Indexing and Slicing of Tensors

Indexing and slicing are used to access or extract specific elements or parts of a tensor.  
This is very important in deep learning for selecting features, batches, channels, and regions of data.

### What is Indexing?

Indexing means selecting **individual elements** of a tensor using their position (index).  
Indexing in tensors starts from **0**.






In [15]:
import torch

# Create a 1D tensor (vector)
x = torch.tensor([10, 20, 30, 40, 50])
x


tensor([10, 20, 30, 40, 50])

### 1. Indexing a 1D Tensor (Vector)


In [18]:
x[0]   # first element


tensor(10)

In [19]:
x[2]   # third element


tensor(30)

In [20]:
x[-1]  # last element


tensor(50)

- Positive index → counts from the beginning  
- Negative index → counts from the end


### 2. Slicing a 1D Tensor

Slicing extracts a **range of elements** from a tensor.
Syntax: `start : end` (end index is excluded)


In [21]:
x[1:4]   # elements from index 1 to 3


tensor([20, 30, 40])

In [22]:
x[:3]    # first three elements


tensor([10, 20, 30])

In [23]:
x[2:]    # elements from index 2 to end


tensor([30, 40, 50])

### Step Size in Slicing

Syntax: `start : end : step`


In [24]:
x[::2]   # every second element


tensor([10, 30, 50])

In [27]:
import torch

x = torch.tensor([10, 20, 30, 40, 50])
torch.flip(x, dims=[0])
 # reverse the tensor


tensor([50, 40, 30, 20, 10])

### 3. Indexing a 2D Tensor (Matrix)


In [28]:
# Create a 2D tensor
m = torch.tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
m


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Accessing Rows


In [29]:
m[0]     # first row


tensor([1, 2, 3])

In [30]:
m[1]     # second row


tensor([4, 5, 6])

### Accessing Columns


In [31]:
m[:, 0]  # first column


tensor([1, 4, 7])

In [32]:
m[:, 2]  # third column


tensor([3, 6, 9])

### 3. Slicing a 2D Tensor


In [33]:
m[0:2, 1:3]  # rows 0–1 and columns 1–2


tensor([[2, 3],
        [5, 6]])

In [34]:
m[:, 1:]     # all rows, columns from index 1 onward


tensor([[2, 3],
        [5, 6],
        [8, 9]])

In [35]:
m[:, 1:]     # all rows, columns from index 1 onward


tensor([[2, 3],
        [5, 6],
        [8, 9]])

### 4. Indexing Higher-Dimensional Tensors

Higher-order tensors are common in deep learning.
Example: 3D tensor (batch, rows, columns)


In [37]:
t = torch.randn(2, 3, 4)
t.shape


torch.Size([2, 3, 4])

### 5. Using Ellipsis (...)

Ellipsis is used to represent missing dimensions.


In [38]:
t[..., 1]   # all elements from last dimension index 1


tensor([[ 0.3199,  0.2449,  0.2132],
        [-2.2484,  0.3037, -0.0742]])

### 6. Boolean Indexing

Boolean indexing selects elements based on conditions.


In [40]:
x = torch.tensor([5, 10, 15, 20])
x[x > 10]


tensor([15, 20])

## Reshaping Tensors

Reshaping means changing the **shape (dimensions)** of a tensor **without changing its data**.  
In deep learning, reshaping is very common when preparing data for neural network layers.


### Why Reshaping is Needed in Deep Learning

- Neural network layers expect inputs in specific shapes  
- Images, text, and batches must be reshaped correctly  
- Helps convert data between layers (e.g., CNN → Fully Connected layer)


### Understanding Tensor Shape

The **shape** of a tensor tells:
- How many dimensions it has  
- How many elements are in each dimension


In [41]:
import torch

x = torch.tensor([1, 2, 3, 4, 5, 6])
x.shape


torch.Size([6])

### 1. Reshaping Using `reshape()`

The `reshape()` function changes the shape of a tensor.


In [42]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
x_reshaped = x.reshape(2, 3)
x_reshaped


tensor([[1, 2, 3],
        [4, 5, 6]])

Rule:  
Total number of elements **must remain the same**.


### 2. Using `-1` to Automatically Infer Size

PyTorch can automatically calculate one dimension.


In [43]:
x.reshape(3, -1)


tensor([[1, 2],
        [3, 4],
        [5, 6]])

Here, PyTorch finds the correct value for `-1`.


### 3. Flattening a Tensor

Flattening means converting a multi-dimensional tensor into a 1D tensor.


In [44]:
m = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

m.flatten()


tensor([1, 2, 3, 4, 5, 6])

### 4. `view()` vs `reshape()`

Both change the shape of a tensor, but they differ internally.


In [46]:
x = torch.tensor([1, 2, 3, 4])
x.view(2, 2)


tensor([[1, 2],
        [3, 4]])

- `view()` works only if tensor memory is contiguous  
- `reshape()` is safer and preferred


### 5. Adding or Removing Dimensions

Sometimes we need to add or remove dimensions.


In [47]:
x = torch.tensor([1, 2, 3])

# Add a new dimension
x.unsqueeze(0)


tensor([[1, 2, 3]])

In [48]:
# Remove dimensions of size 1
x.unsqueeze(0).squeeze()


tensor([1, 2, 3])

## Tensor Arithmetic Operations

Tensor arithmetic operations are mathematical operations performed on tensors.  
These operations are applied **element-wise** and are heavily used in deep learning for computing outputs, losses, and gradients.


In [49]:
import torch

a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])


In [50]:
# Addition
a + b


tensor([5, 7, 9])

In [51]:
# Subtraction
a - b


tensor([-3, -3, -3])

In [52]:
# Multiplication (element-wise)
a * b


tensor([ 4, 10, 18])

In [53]:
# Division
a / b


tensor([0.2500, 0.4000, 0.5000])

### Matrix Multiplication


In [54]:
m1 = torch.tensor([[1, 2],
                   [3, 4]])
m2 = torch.tensor([[5, 6],
                   [7, 8]])

torch.matmul(m1, m2)


tensor([[19, 22],
        [43, 50]])

## Broadcasting 

Broadcasting allows arithmetic operations between tensors of **different shapes**.


### Rules of Broadcasting
1. Compare tensor shapes from right to left  
2. Dimensions are compatible if they are equal or one of them is 1  
3. Smaller tensor is automatically expanded


In [55]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
y = torch.tensor([1, 2, 3])

x + y


tensor([[2, 4, 6],
        [5, 7, 9]])

Here, `y` is broadcast across rows of `x`.


Broadcasting avoids copying data and improves performance.


## Need for Non-Linear Activation Functions

Without non-linear activation functions:
- Neural networks become linear models
- Stacking layers has no added benefit
- Complex patterns cannot be learned

Activation functions introduce **non-linearity**, enabling deep networks to learn complex relationships.


## Sigmoid Activation Function

The sigmoid activation function maps input values to the range (0, 1).

Formula:
σ(x) = 1 / (1 + e⁻ˣ)

Uses:
- Binary classification
- Output layer for probability prediction


In [58]:
import torch.nn.functional as F

x = torch.tensor([-3.0, -1.0, 0.0, 1.0, 3.0])
F.sigmoid(x)




tensor([0.0474, 0.2689, 0.5000, 0.7311, 0.9526])

## Sigmoid Activation Function

![Sigmoid Activation Function](https://media.geeksforgeeks.org/wp-content/uploads/20241029120537926197/Sigmoid-Activation-Function.png)


### Properties of Sigmoid
- Output range: (0, 1)
- Smooth and differentiable
- Can cause vanishing gradient for large values

## 2. Hyperbolic Tangent (tanh) Activation Function



The **tanh** function maps input values to the range **(-1, 1)**.  
It is zero-centered, which often leads to faster convergence than Sigmoid for hidden layers.


In [ ]:
import torch
import matplotlib.pyplot as plt

# Generate input values
x = torch.linspace(-10, 10, 100)

# Apply tanh activation
y_tanh = torch.tanh(x)

# Plot the tanh function
plt.plot(x.numpy(), y_tanh.numpy())
plt.title("tanh Activation Function (Code Plot)")
plt.xlabel("x")
plt.ylabel("tanh(x)")
plt.grid(True)
plt.show()


![tanh Activation Function](https://media.geeksforgeeks.org/wp-content/uploads/20241029120618881107/Tanh-Activation-Function.png)


## 3. Rectified Linear Unit (ReLU)

![ReLU Activation Function](https://media.geeksforgeeks.org/wp-content/uploads/20241029120652402777/relu-activation-function.png)

ReLU is the most popular activation function in deep learning.  
It outputs zero for negative values and the input for positive values.


In [ ]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

# Generate input values
x = torch.linspace(-10, 10, 100)

# Apply ReLU activation
y_relu = F.relu(x)

# Plot the ReLU function
plt.plot(x.numpy(), y_relu.numpy())
plt.title("ReLU Activation Function (Code Plot)")
plt.xlabel("x")
plt.ylabel("ReLU(x)")
plt.grid(True)
plt.show()



## 4. Softmax Function (Multi-class Classification)

![Softmax Function](https://media.geeksforgeeks.org/wp-content/uploads/20241029120724445438/softmax.png)

Softmax converts raw scores (logits) into **probabilities** that sum to 1.  
It is used in the **output layer for multi-class classification**.


In [2]:
import torch
import torch.nn.functional as F

scores = torch.tensor([2.0, 1.0, 0.1])

# Apply Softmax
y_softmax = F.softmax(scores, dim=0)

y_softmax


tensor([0.6590, 0.2424, 0.0986])

The output shows the **probabilities** of each class.  
Softmax is ideal for problems with >2 classes.


# Summary of Activation Functions

| Activation | Output Range | Why Used |
|------------|--------------|-----------|
| Sigmoid    | (0, 1)       | Binary classification, probability output |
| tanh       | (-1, 1)      | Hidden layers, zero-centered |
| ReLU       | [0, ∞)       | Deep models, fast convergence |
| Softmax    | (0, 1)       | Multi-class classification |
